import fs from 'node:fs'

const src = fs.readFileSync(new URL('../src/index.ts', import.meta.url), 'utf8')
const pkg = JSON.parse(fs.readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
const wrangler = fs.readFileSync(new URL('../wrangler.jsonc', import.meta.url), 'utf8')
const checks = []
const must = (ok, msg) => { checks.push([!!ok, msg]); if (!ok) process.exitCode = 1 }

must(/const SERVICE = 'math-auth'/.test(src), 'service is math-auth')
const legacyName = 'grade3-' + 'math-auth'
must(!(src + wrangler).includes(legacyName), 'legacy Worker name absent')
must(/const PASSWORD_ITERATIONS = 600_000/.test(src), 'PBKDF2-SHA256 uses 600,000 iterations')
must(/PASSWORD_PEPPER/.test(src), 'password pepper is required')
must(/new Set\(\[env\.SESSION_SECRET, env\.DATA_ENCRYPTION_KEY, env\.PASSWORD_PEPPER\]\)\.size !== 3/.test(src), 'cryptographic secrets must be distinct')
must(/CONTEXT_PASSWORD_TERMS/.test(src) && /purple comet 47 river!/.test(src), 'published example and service-specific weak passwords are blocked')
must(/crypto\.subtle\.encrypt\(\{ name: 'AES-GCM'/.test(src), 'AES-GCM protects sealed tokens/TOTP')
must(/ttlByType/.test(src) && /session: SESSION_TTL_SEC/.test(src), 'token TTL is validated per token type')
must(/lastUsedCounter/.test(src), 'TOTP replay counter is stored')
must(/\/api\/logout/.test(src) && /sessionMatches/.test(src), 'server-side session revocation is implemented')
must(/PRIVACY_NOTICE_VERSION/.test(src) && /consent: \{ noticeVersion:/.test(src), 'privacy acknowledgement is persisted in the learner record')
must(/const body = \{ \.\.\.payload, iss: SERVICE, iat: now, exp: now \+ ttlSec \}/.test(src), 'sealed-token reserved metadata cannot be overridden by payload fields')
must(/appTokenCache\.scope === cacheScope/.test(src), 'GitHub App token cache is scope-keyed')
must(/\^\[a-f0-9\]\{40,64\}\$/i.test(src), 'GitHub content SHA is validated')
must(/read:user:\$\{String\(p\.sub\)\}/.test(src), 'authenticated profile reads are rate-limited')
must(/MAX_BODY_BYTES/.test(src) && /body\.getReader\(\)/.test(src), 'request body is streamed with a hard limit')
must(/rawToken\.length < 32 \|\| rawToken\.length > 4096/.test(src), 'sealed token input length is bounded before decoding')
must(/TextDecoder\('utf-8', \{ fatal: true \}\)/.test(src), 'request JSON must be valid UTF-8')
must(/const allowed = origin === c\.env\.FRONTEND_ORIGIN/.test(src), 'CORS origin is exact in production')
must(/const uri = `otpauth:\/\/totp\/\$\{label\}\?secret=\$\{secret\}&issuer=\$\{encodeURIComponent\(ISSUER\)\}`/.test(src), 'TOTP provisioning URI uses the compact standard-default form required by the local QR encoder')
must(!/localhost|127\.0\.0\.1/.test(src.slice(src.indexOf("app.use('*'"), src.indexOf('app.onError'))), 'production CORS has no localhost exception')
must(/AUTH_IP_RATE_LIMITER/.test(src) && /AUTH_ACCOUNT_RATE_LIMITER/.test(src), 'separate IP and account auth rate limits exist')
must(/PROGRESS_RATE_LIMITER/.test(src), 'progress rate limit exists')
must(/typeof raw\.correct !== 'boolean'/.test(src), 'progress correctness rejects type coercion')
must(/RESERVED_TOPIC_KEYS/.test(src), 'prototype-pollution topic keys are rejected')
must(/permissions: \{ contents: 'write' \}/.test(src), 'GitHub App token is narrowed to Contents write')
must(/repositories: \[env\.GITHUB_REPO\]/.test(src), 'GitHub App token is narrowed to the data repository')
must(!/eval\s*\(|new Function\s*\(|document\.write/.test(src), 'dangerous dynamic-code/browser sinks absent from backend')
must(pkg.dependencies?.hono === '4.12.32', 'Hono is exact-pinned')
must(pkg.devDependencies?.wrangler === '4.114.0', 'Wrangler is exact-pinned')
must(/"name"\s*:\s*"math-auth"/.test(wrangler), 'Wrangler Worker name is math-auth')
must(/AUTH_IP_RATE_LIMITER/.test(wrangler) && /AUTH_ACCOUNT_RATE_LIMITER/.test(wrangler) && /PROGRESS_RATE_LIMITER/.test(wrangler), 'all rate-limit bindings are configured')

for (const [ok, msg] of checks) console.log(`${ok ? 'PASS' : 'FAIL'}  ${msg}`)
if (process.exitCode) throw new Error('Security regression check failed')
